# Docker compose file for testing production builds during development
version: "3.8"
services:
  next-app:
    build:
      context: ./src # folder of the app on my machine
      target: runner
      dockerfile: Dockerfile
    container_name: next-app
    restart: always
    volumes:
      - ./src:/next-app # folder of the app on my machine : folder of the app on the container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://mongodb:27017/dblp-analysis-tool"
      SESSION_SECRET: "9b4f808b903433f7938ead04bb7b5f7aa8b2da1a8af73ec44a0d8d6c0c6b4ef2c06f92b8362ba40c536beca38e03c5759b8bf021aac7324f96ae413670ad9083"

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
